In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [10]:
sequ = nn.Sequential(nn.Linear(20, 100),
                    nn.Linear(100, 10))
param = sequ.parameters()

In [11]:
for p in param:
    print(f'param shape: {p.shape}')

param shape: torch.Size([100, 20])
param shape: torch.Size([100])
param shape: torch.Size([10, 100])
param shape: torch.Size([10])


In [171]:
import torch.nn.functional as F
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(3, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)
    def forward(self, x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))

In [172]:
model = Model()
param = model.parameters()
model(torch.randn(1, 3, 224, 224)).mean().backward()
grads = []
for param in model.parameters():
    grads.append(param.grad.view(-1))
# grads = torch.cat(grads)

In [173]:
grads

[tensor([ 4.9132e-05, -1.2128e-04,  8.4268e-04,  ...,  9.7058e-04,
          9.8631e-05, -1.2243e-03]),
 tensor([ 5.1480e-03, -3.9538e-03,  7.2601e-03,  4.2951e-03,  6.3032e-03,
         -9.8259e-03, -2.2663e-04,  8.1069e-04,  1.3059e-02,  5.5658e-03,
          2.7428e-03,  4.7035e-03, -8.6752e-03,  4.2525e-05,  1.4294e-03,
          5.9643e-03,  2.2848e-02,  2.9080e-03,  6.3690e-03,  8.8614e-03]),
 tensor([0.0047, 0.0045, 0.0044,  ..., 0.0045, 0.0044, 0.0045]),
 tensor([0.0232, 0.0173, 0.0186, 0.0407, 0.0185, 0.0106, 0.0253, 0.0122, 0.0208,
         0.0149, 0.0242, 0.0167, 0.0477, 0.0092, 0.0063, 0.0111, 0.0035, 0.0079,
         0.0148, 0.0226])]

In [151]:
import torchvision.models as models
model = models.resnet18()
# Calculate dummy gradients
model(torch.randn(1, 3, 224, 224)).mean().backward()
# model(torch.randn(1, 3, 224, 224)).backward()
grads = []
for param in model.parameters():
    grads.append(param.grad.view(-1))
#     grads.append(param.grad)
# grads = torch.cat(grads)

In [175]:
from torch.autograd import Variable
ndarray = 3
fu=Variable(torch.from_numpy(ndarray).float(), requires_grad=False)

TypeError: expected np.ndarray (got int)

In [156]:
grads

[tensor([-9.4115e-04, -2.7185e-03,  5.5017e-03,  ...,  4.9478e-03,
         -4.8975e-07, -6.4486e-03]),
 tensor([ 2.3311e-05, -1.4934e-05, -8.7522e-04,  7.9454e-04,  5.9666e-04,
          1.1153e-04, -1.3161e-03,  1.8044e-03,  4.7826e-04,  1.4813e-03,
         -6.2917e-04, -1.0096e-04, -5.7827e-05, -1.6928e-03,  9.0545e-04,
         -4.1971e-05, -7.5355e-04, -2.0427e-03, -2.0614e-03, -3.1500e-04,
         -1.9640e-03, -1.2198e-03,  8.0995e-04,  1.8062e-04, -1.8602e-03,
          2.9766e-04,  2.5156e-04,  1.3954e-03,  1.0867e-03, -4.4065e-04,
          9.2414e-04, -4.2311e-04, -6.7234e-04, -1.2065e-03,  3.8914e-04,
         -2.2391e-03,  1.6788e-03, -6.0662e-04, -8.3775e-04, -3.1679e-04,
          1.0854e-03,  6.8153e-04, -8.2648e-04, -9.1042e-04,  9.4185e-04,
          1.3611e-03,  1.3705e-04, -1.0987e-03,  3.8374e-04, -6.7040e-04,
         -3.8890e-04,  1.7949e-03,  2.2919e-03, -1.4295e-03,  1.2412e-03,
          5.3039e-04, -7.6908e-04, -1.7487e-04,  1.4241e-04,  1.8040e-03,
        

In [152]:
fu = torch.tensor(np.array(1))
fu

tensor(1)

In [155]:
torch.tensor(grads)

ValueError: only one element tensors can be converted to Python scalars

In [124]:
from torchsummary import summary
summary(model, (3, 28, 28))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1           [-1, 64, 14, 14]           9,408
       BatchNorm2d-2           [-1, 64, 14, 14]             128
              ReLU-3           [-1, 64, 14, 14]               0
         MaxPool2d-4             [-1, 64, 7, 7]               0
            Conv2d-5             [-1, 64, 7, 7]           4,096
       BatchNorm2d-6             [-1, 64, 7, 7]             128
              ReLU-7             [-1, 64, 7, 7]               0
            Conv2d-8             [-1, 64, 7, 7]          36,864
       BatchNorm2d-9             [-1, 64, 7, 7]             128
             ReLU-10             [-1, 64, 7, 7]               0
           Conv2d-11            [-1, 256, 7, 7]          16,384
      BatchNorm2d-12            [-1, 256, 7, 7]             512
           Conv2d-13            [-1, 256, 7, 7]          16,384
      BatchNorm2d-14            [-1, 25

In [112]:
print(model)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [100]:
flag = isinstance(param, list)
flag

False

In [101]:
for p in param:
    t = p.data
    print(t.size())

torch.Size([20, 1, 5, 5])
torch.Size([20])
torch.Size([20, 20, 5, 5])
torch.Size([20])


In [72]:
fu = torch.Tensor(20, 1, 5, 5)
fu.size()

torch.Size([20, 1, 5, 5])